//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int Id_shop { get; set; }
        public Nullable<int> Id_User { get; set; }
        public Nullable<decimal> SumOrder { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual User User { get; set; }
    }
}
