//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Id { get; set; }
        public Nullable<int> Id_User { get; set; }
        public Nullable<int> Id_Client { get; set; }
        public Nullable<int> Id_Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> PayPrice { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Type_Procedur Type_Procedur { get; set; }
        public virtual User User { get; set; }
    }
}
