//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Id { get; set; }
        public Nullable<int> Id_User { get; set; }
        public Nullable<int> Id_Client { get; set; }
        public Nullable<int> Id_Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> PayPrice { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Type_Procedur Type_Procedur { get; set; }
        public virtual User User { get; set; }
    }
}
